# Generated by Django 5.0 on 2024-01-01 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('guid', models.UUIDField(primary_key=True, serialize=False)),
                ('public_unique_identifier', models.PositiveIntegerField(unique=True)),
                ('range_from', models.PositiveSmallIntegerField()),
                ('range_to', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('guid', models.UUIDField(primary_key=True, serialize=False)),
                ('color', models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('GREEN', 'Green'), ('PURPLE', 'Purple')], max_length=6)),
                ('number', models.PositiveSmallIntegerField()),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='number_generator.generation')),
            ],
        ),
    ]
