# Generated by Django 5.0 on 2024-01-03 02:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='generation',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='generation',
            name='public_unique_identifier',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='number',
            name='generation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='number_generator.generation', to_field='guid'),
        ),
        migrations.AlterField(
            model_name='number',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
